// src/utils/mockData.js
export const mockUser = {
  id: 'user_001',
  name: 'John Analyst',
  email: 'john@policy360.gov',
  sector: 'education',
  organization: 'Ministry of Education',
  role: 'Policy Analyst',
  createdAt: '2024-01-15',
};

export const mockPolicies = [
  {
    id: 'policy_001',
    title: 'Digital Education Transformation',
    description: 'Comprehensive policy to digitize educational infrastructure and implement e-learning platforms across all schools.',
    sector: 'education',
    status: 'active',
    progress: 75,
    stage: 'implementation',
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    budget: 500000,
    stakeholders: 15,
    color: '#4CAF50',
    objectives: [
      'Digitize 1000 schools',
      'Train 5000 teachers',
      'Provide tablets to 50,000 students',
      'Improve digital literacy by 40%',
    ],
  },
  {
    id: 'policy_002',
    title: 'Universal Healthcare Access',
    description: 'Policy to ensure all citizens have access to basic healthcare services and insurance coverage.',
    sector: 'health',
    status: 'analysis',
    progress: 40,
    stage: 'analysis',
    startDate: '2024-02-01',
    endDate: '2024-12-31',
    budget: 2500000,
    stakeholders: 28,
    color: '#F44336',
    objectives: [
      'Cover 95% population',
      'Reduce out-of-pocket expenses',
      'Improve hospital infrastructure',
      'Increase doctor-patient ratio',
    ],
  },
  {
    id: 'policy_003',
    title: 'Sustainable Farming Initiative',
    description: 'Promote organic farming and sustainable agricultural practices to ensure food security.',
    sector: 'agriculture',
    status: 'ideation',
    progress: 25,
    stage: 'ideation',
    startDate: '2024-03-01',
    endDate: '2025-02-28',
    budget: 800000,
    stakeholders: 12,
    color: '#FF9800',
    objectives: [
      'Train 10,000 farmers',
      'Increase organic farming by 30%',
      'Reduce pesticide use by 50%',
      'Improve crop yield by 20%',
    ],
  },
];